<?php
/**
 * Ultimate_ModuleCreator extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE_UMC.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category       Ultimate
 * @package        Ultimate_ModuleCreator
 * @copyright      Copyright (c) 2014
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */ 
/**
 * tooltip template
 * @category    Ultimate
 * @package     Ultimate_ModuleCreator
 * @author      Marius Strajeru <ultimate.module.creator@gmail.com>
 */
?>
<div class="f-right ">
    <a class="field-tooltip" style="cursor:pointer;z-index:0" onclick="Dialog.alert('<?php echo $this->jsQuoteEscape($this->htmlEscape($this->getMessage()))?>', {className:'magento',width:300,okLabel: '<?php echo Mage::helper('modulecreator')->__('OK. I got it!')?>', buttonClass: 'scalable',id: '<?php echo md5($this->getMessage())?>', title: '<?php echo $this->jsQuoteEscape($this->htmlEscape($this->getTitle()))?>'});return false;"></a>
</div>
