<?php
/**
 * Ultimate_ModuleCreator extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE_UMC.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category       Ultimate
 * @package        Ultimate_ModuleCreator
 * @copyright      Copyright (c) 2014
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * attribute template
 *
 * @category    Ultimate
 * @package     Ultimate_ModuleCreator
 * @author      Marius Strajeru <ultimate.module.creator@gmail.com>
 */
?>
<?php $_id = $this->getEntityId().'_'.$this->getIncrement();?>
<?php $_attribute = $this->getAttributeInstance();?>
<div class="entry-edit modulecreator-attribute" id="attribute_<?php echo $_id?>">
    <?php echo $this->getFormHtml()?>
    <?php /** @var Ultimate_ModuleCreator_Model_Attribute $_attribute */?>
    <?php if ($_attribute->getIsName()) : ?>
        <script type="text/javascript">
            document.observe("dom:loaded", function() {
                nameAttributes[<?php echo $this->getEntityId();?>] = <?php echo $this->getIncrement();?>
            });
        </script>
    <?php endif;?>
</div>
